DROP TABLE ODONTOLOGOS IF EXISTS;

CREATE TABLE ODONTOLOGOS (
ID INT AUTO_INCREMENT PRIMARY KEY,
NUMEROMATRICULA INT NOT NULL,
NOMBRE VARCHAR(50) NOT NULL,
APELLIDO VARCHAR(50) NOT NULL
);

INSERT INTO ODONTOLOGOS VALUES (DEFAULT, 202020, 'JUAN', 'PEREZ'),
(DEFAULT, 303030, 'JUANA', 'DELGADO'),
(DEFAULT, 404040, 'PEPITO', 'PEREZ');